
services:
  frontend:
    build: 
      context: ./frontend  # Specify the build context
    ports:
      - '8001:80'  # Exposes the frontend on port 8001
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory to /app in the container for live updates
    depends_on:
      - backend  # Ensures that the backend service starts before the frontend
      # - db

    # Docker Compose Watch
    develop:
      watch:
        - action: rebuild # rebuild image with updated code
          path: ./frontend
          target: /app


  backend:
    build:
      context: ./backend  # Specify the build context
    ports:
      - '8002:5000'  # Exposes the backend on port 8002
    
    # Docker Compose Watch
    develop:
      watch:
        - action: sync+restart # copy code to container and restart container
          path: ./backend
          target: /app
    
    # Docker Swarm related conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the backend to access Docker socket
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  
  proxy:
    build: ./proxy
    ports: ['8090:80']
    
    # Docker Compose Watch
    develop:
      watch: 
        - action: sync+restart # copy code to container and restart container
          path: ./proxy/default.conf
          target: /etc/nginx/conf.d

  # db:
  #   image: mongo
    # volumes:
    #   - 