
# STAGE 1

FROM python:3.12 AS build

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# STAGE 2
FROM python:3.12-slim

WORKDIR /app

COPY --from=build /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

COPY --from=build /app /app

EXPOSE 5000

CMD ["python", "app.py"]